import React, { createContext, useState, useContext } from 'react';

// Create and export the context
export const LanguageContext = createContext(null);

// Define available languages
const languages = {
  en: {
    name: 'English',
    flag: '🇺🇸',
    translations: {
      // Navigation & Common
      home: 'Home',
      about: 'About Us',
      blog: 'Resources',
      dashboard: 'Dashboard',
      login: 'Login',
      signup: 'Sign Up',
      resources: 'Resources',
      findTeacher: 'Find a Teacher',
      becomeTeacher: 'Become a Teacher',
      logout: 'Logout',
      contact: 'Contact',
      
      // Auth Forms
      welcomeBack: 'Welcome Back!',
      continueJourney: 'Sign in to continue your learning journey with LesonPaw',
      email: 'Email',
      password: 'Password',
      forgotPassword: 'Forgot password?',
      enterEmail: 'Enter your email',
      enterPassword: 'Enter your password',
      validate: 'Validate',
      captchaText: 'Enter the captcha text',
      newToSite: 'New to LesonPaw?',
      createAccount: 'Create an account',
      successLogin: 'User Login Successful!',
      failedLogin: 'Login Failed',
      tryAgain: 'Try Again',
      
      // Footer
      quickLinks: 'Quick Links',
      subjects: 'Subjects',
      contactUs: 'Contact Us',
      teacherGuide: 'Teacher Guide',
      studentGuide: 'Student Guide',
      connectingStudents: 'Connecting students with professional teachers across Haiti since 2023',
      allRightsReserved: '© 2025 LesonPaw. All rights reserved.',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      cookies: 'Cookies',
      
      // Home Page
      transformingEducation: 'Transforming Education',
      inHaiti: 'in Haiti',
      buildingBridges: "Unlock your potential with expert educators who inspire. Join thousands of successful students on Haiti's premier learning platform. Your journey to excellence starts here!",
      getStarted: 'Get Started Now',
      
      // About Page
      ourPurpose: 'Our Purpose',
      empoweringEducation: 'Empowering education through innovation and accessibility',
      forStudents: 'For Students',
      forTutors: 'For Tutors',
      accessToTutors: 'Access to qualified tutors across multiple subjects',
      flexibleScheduling: 'Flexible scheduling to fit your needs',
      personalizedLearning: 'Personalized learning experience',
      progressTracking: 'Progress tracking and performance analytics',
      buildProfile: 'Build your teaching profile and reputation',
      setSchedule: 'Set your own schedule and rates',
      teachingResources: 'Access to teaching resources and materials',
      securePayment: 'Secure payment processing',
      
      // Trust & Security
      trustAndSecurity: 'Trust & Security',
      yourSafety: 'Your safety and success are our top priorities',
      verifiedTutors: 'Verified Tutors',
      support247: '24/7 Support',
      satisfactionGuarantee: 'Satisfaction Guarantee',
      tutorsVerified: 'All our tutors undergo thorough background checks and verification processes',
      supportAvailable: 'Our dedicated support team is always available to assist you',
      qualityEducation: 'We ensure quality education and student satisfaction in every session',
      
      // Subjects
      mathematics: 'Mathematics',
      sciences: 'Sciences',
      languages: 'Languages',
      history: 'History',
      computerScience: 'Computer Science',
      artsMusic: 'Arts & Music',
      
      // Stats
      studentsHelped: 'Students Helped',
      successfulLearners: 'Successful learners who achieved their goals',
      expertTutors: 'Expert Tutors',
      qualifiedEducators: 'Qualified educators ready to help',
      subjectsCovered: 'Subjects Covered',
      diverseTopics: 'Diverse range of academic topics',
      successRate: 'Success Rate',
      satisfactionRate: 'Student satisfaction rate',
      
      // Values
      ourValues: 'Our Core Values',
      principlesGuide: 'Principles that guide our mission to transform education',
      integrity: 'Integrity',
      integrityDesc: 'We maintain the highest standards of professional conduct',
      innovation: 'Innovative Learning',
      innovationDesc: 'Leveraging technology to make education more accessible and engaging for everyone.',
      growth: 'Growth',
      growthDesc: 'Fostering continuous learning and development',
      excellence: 'Excellence',
      excellenceDesc: 'Striving for the best in everything we do',
      
      // Call to Action
      readyToTransform: 'Ready to Transform Your Learning Journey?',
      joinThousands: 'Join thousands of students and tutors who are already part of our growing community',

      // How It Works Section
      howItWorks: 'How It Works',
      searchTeacher: 'Search',
      searchTeacherDesc: 'Find the perfect teacher based on your needs and location in Haiti.',
      connect: 'Connect',
      connectDesc: 'Schedule lessons at times that work for your availability.',
      learn: 'Learn',
      learnDesc: 'Receive personalized instruction and achieve your goals.',
      platformDesc: 'Our platform makes it easy to connect students with qualified teachers in Haiti',
      readyToStart: 'Ready to start your learning journey or offer your teaching services?',
      
      // Why Choose Us Section
      whyChooseUs: 'Why Choose LessonPaw',
      committedToEducation: "We're committed to making quality education accessible throughout Haiti",
      verifiedTeachers: 'Verified Teachers',
      verifiedTeachersDesc: 'All teachers are verified for credentials and expertise in their subjects.',
      studentCount: '5,000+ Students',
      studentCountDesc: 'Join thousands of students who have found their perfect teacher match.',
      qualityGuarantee: 'Quality Guarantee',
      qualityGuaranteeDesc: 'We ensure high-quality teaching or offer a replacement at no extra cost.',
      safePayments: 'Safe Payments',
      safePaymentsDesc: 'Secure payment options including mobile money popular in Haiti.',
      
      // Teacher Section
      meetExperts: 'Meet Our Expert Tutors',
      teacherDesc: 'Learn from experienced educators who are passionate about helping students succeed',
      
      // Success Stories Section
      successStories: 'Our Success Stories',
      successStoriesDesc: 'Discover how our platform has transformed learning experiences and helped students achieve their goals',
      viewAllStories: 'View All Success Stories',
      noStories: 'No success stories to display yet.',
      
      // Support Section
      support: 'Support',
      supportDesc: 'Need help? Our support team is here for you',
      contactSupport: 'Contact Support',
      supportEmail: 'Email Support',
      supportPhone: 'Phone Support',
      supportChat: 'Live Chat',
      supportHours: 'Support Hours',
      supportAvailability: 'Support Available 24/7',
      supportResponse: 'Typical response time: 2 hours',
      supportTicket: 'Create Support Ticket',
      supportFAQ: 'FAQ',
      supportHelp: 'Need Support?',
      supportTeam: 'We are here to Help',
      
      // Message Component
      pleaseEnterMessage: 'Please enter a message',
      sent: 'Sent',
      messageSent: 'Message sent',
      error: 'Error',
      failedToSendMessage: 'Failed to send message',
      quickResponse: 'Quick Response',
      writeMessage: 'Write your message here...',
      sendMessage: 'Send Message',
      signInToMessage: 'Sign in to Send a Message',
      pleaseLoginMessage: 'Please log in to your account to send us a message.',
      
      // What is LesonPaw Section
      whatIsLesonPaw: 'What is',
      connectingStudents: 'Connecting students with professional teachers across Haiti since 2024',
      qualityEducation: 'Quality Education',
      qualityEducationDesc: 'We provide access to high-quality education through our network of verified professional teachers.',
      connecting: 'Building Connections',
      connectingDesc: 'Creating meaningful connections between students and teachers to foster a collaborative learning environment.',
      innovativeLearning: 'Innovative Learning',
      innovativeLearningDesc: 'Using technology to make education more accessible and engaging for everyone.',
      lesonPawMission: 'Our mission is to transform education in Haiti by making quality learning accessible to all students through our innovative platform.',

      // Contact Page
      getInTouch: 'Get in Touch with',
      contactSubtitle: "We're here to help! Send us a message and we'll respond within 24 business hours.",
      fullName: 'Full Name',
      nameRequired: 'Name is required',
      emailRequired: 'Email is required',
      invalidEmail: 'Invalid email address',
      phone: 'Phone Number',
      optional: 'Optional',
      subject: 'Subject',
      subjectRequired: 'Subject is required',
      message: 'Message',
      messageRequired: 'Message is required',
      messageMinLength: 'Message must be at least 20 characters',
      attachments: 'Attachments',
      fileUploadInfo: 'Max file size: 5MB. Supported formats: PDF, DOC, DOCX, JPG, PNG',
      verifyCaptcha: 'Verify Captcha',
      enterCaptcha: 'Enter captcha text',
      captchaValidated: 'Captcha Validated!',
      captchaRequired: 'Captcha Required',
      pleaseVerifyCaptcha: 'Please verify the captcha before submitting',
      sending: 'Sending...',
      responseTime: 'We will get back to you within 24 business hours.',
      submissionFailed: 'Submission Failed',
      tryAlternativeContact: 'Please try again later or use alternative contact methods.',
      businessHours: 'Business Hours',
      mondayFriday: 'Monday - Friday',
      saturday: 'Saturday',
      sunday: 'Sunday',
      closed: 'Closed',
      timeZone: 'All times are in Eastern Time (ET)',
      contactInfo: 'Contact Information',
      address: 'Address',
      connectWithUs: 'Connect With Us',
      ourLocation: 'Our Location',
      getDirections: 'Get Directions',

      // Dashboard Menu
      manageProfile: 'Manage Profile',
      myBookings: 'My Bookings',
      joinAsTeacher: 'Join as Teacher',
      postJob: 'Post Job',
      myPosts: 'My Posts',
      availableJobs: 'Available Jobs',
      manageServices: 'Manage Services',
      manageUsers: 'Manage Users',
      allTutors: 'All Tutors',
      showMessages: 'Show Messages',
      addTutor: 'Add Tutor',
      applications: 'Applications',
      payments: 'Payments',
      analytics: 'Analytics',
      students: 'Students',
      allJobs: 'All Jobs',
      allServices: 'All Services',
      story: 'Story',
      manageStory: 'Manage Story',
      addBlog: 'Add Blog',
      editBlog: 'Edit Blog',
      confirmation: 'Confirmations',
      menu: 'Menu',

      // Find Teacher Guide
      findPerfectTeacher: 'Find Your Perfect Teacher',
      findTeacherDesc: 'Discover expert educators who will guide you towards academic excellence and personal growth',
      smartSearch: 'Smart Search',
      smartSearchDesc: 'Our intelligent matching system helps you find the perfect teacher based on your learning goals, preferred subjects, and schedule.',
      expertVerification: 'Expert Verification',
      expertVerificationDesc: 'Every teacher undergoes a rigorous verification process. View detailed profiles with verified credentials, experience, and student reviews.',
      flexibleLearning: 'Flexible Learning',
      flexibleLearningDesc: 'Choose between online or in-person sessions. Schedule lessons that fit your lifestyle with our easy-to-use booking system.',
      personalizedExperience: 'Personalized Experience',
      personalizedExperienceDesc: 'Enjoy customized learning plans, progress tracking, and continuous support throughout your educational journey.',
      verifiedTeachers: 'Verified Teachers',
      verifiedTeachersCount: 'Verified Teachers',
      subjectsOffered: 'Subjects Offered',
      studentSatisfaction: 'Student Satisfaction',
      learningJourneyStart: 'Your Learning Journey Starts Here',
      whyStudentsChooseUs: 'Why Students Choose Us',
      expertTeachers: 'Expert Teachers',
      expertTeachersDesc: 'Learn from certified professionals with proven track records',
      modernLearningTools: 'Modern Learning Tools',
      modernLearningToolsDesc: 'Access cutting-edge educational resources and technology',
      communitySupport: 'Community Support',
      communitySupportDesc: 'Join a vibrant learning community of students and educators',
      startLearningToday: 'Start Learning Today',
      learnMoreAboutUs: 'Learn More About Us',

      // Become Teacher Guide
      becomeExpertTeacher: 'Become an Expert Teacher',
      becomeTeacherDesc: 'Share your knowledge, inspire students, and build a rewarding teaching career on our platform',
      teacherProfile: 'Build Your Profile',
      buildProfileDesc: 'Create a compelling teaching profile showcasing your expertise, teaching methodology, and professional achievements.',
      qualityVerification: 'Quality Verification',
      qualityVerificationDesc: 'Our thorough verification process ensures high teaching standards. Submit your credentials and teaching certifications.',
      customizeTeaching: 'Customize Your Teaching',
      customizeTeachingDesc: 'Set your teaching preferences, rates, and availability. Choose between online and in-person instruction options.',
      startJourney: 'Start Your Journey',
      startJourneyDesc: 'Connect with students, deliver engaging lessons, and grow your teaching business on our platform.',
      professionalGrowth: 'Professional Growth',
      professionalGrowthDesc: 'Access professional development resources and build your teaching portfolio',
      teachingTools: 'Teaching Tools',
      teachingToolsDesc: 'Utilize our advanced teaching platform and resources',
      careerDevelopment: 'Career Development',
      careerDevelopmentDesc: 'Expand your reach and grow your teaching career',
      flexibleSchedule: 'Flexible Schedule',
      flexibleScheduleDesc: 'Work on your own terms',
      platformSupport: 'Platform Support',
      platformSupportDesc: 'Always here to help',
      earningPotential: 'Earning Potential',
      earningPotentialDesc: 'Set your own rates',
      teachingJourneyBegins: 'Your Teaching Journey Begins Here',
      teachingBenefits: 'Benefits of Teaching With Us',
      readyToTeach: 'Ready to Start Your Teaching Journey?',
      joinTeacherCommunity: 'Join our community of passionate educators and make a difference in students\' lives',
      applyAsTeacher: 'Apply as a Teacher',
      learnMoreTeaching: 'Learn More About Teaching',

      // Blog Page
      discoverKnowledge: 'Discover',
      insights: 'Insights',
      blogDescription: 'Explore insightful articles, expert tips, and inspiring stories from our community of educators and learners.',
      searchBlogsPlaceholder: 'Search articles by title, category, or content...',
      popular: 'Popular',
      teachingTips: 'Teaching Tips',
      studyGuides: 'Study Guides',
      learningResources: 'Learning Resources',
      studentSuccess: 'Student Success',
      allCategories: 'All Categories',
      noPostsFound: 'No Posts Found',
      adjustSearchOrCategory: 'Try adjusting your search or category filter',
      readMore: 'Read More',
      tags: 'Tags',
      education: 'Education',
      technology: 'Technology',
      learning: 'Learning',
      teaching: 'Teaching',
      students: 'Students',
      tips: 'Tips',
      recentPosts: 'Recent Posts',
      failedToLoadBlogs: 'Failed to load blogs',
      errorLoadingBlogs: 'Error Loading Blogs',
      tryAgainLater: 'Please try again later',
      readTime: 'Read time',
      author: 'Author',
      relatedTopics: 'Related Topics',
    }
  },
  es: {
    name: 'Español',
    flag: '🇪🇸',
    translations: {
      // Navigation & Common
      home: 'Inicio',
      about: 'Sobre Nosotros',
      blog: 'Recursos',
      dashboard: 'Panel de Control',
      login: 'Iniciar Sesión',
      signup: 'Registrarse',
      resources: 'Recursos',
      findTeacher: 'Encontrar Profesor',
      becomeTeacher: 'Conviértete en Profesor',
      logout: 'Cerrar Sesión',
      contact: 'Contacto',
      
      // Auth Forms
      welcomeBack: '¡Bienvenido de Nuevo!',
      continueJourney: 'Inicia sesión para continuar tu viaje de aprendizaje con LesonPaw',
      email: 'Correo Electrónico',
      password: 'Contraseña',
      forgotPassword: '¿Olvidaste tu contraseña?',
      enterEmail: 'Ingresa tu correo electrónico',
      enterPassword: 'Ingresa tu contraseña',
      validate: 'Validar',
      captchaText: 'Ingresa el texto del captcha',
      newToSite: '¿Nuevo en LesonPaw?',
      createAccount: 'Crear una cuenta',
      successLogin: '¡Inicio de sesión exitoso!',
      failedLogin: 'Error al iniciar sesión',
      tryAgain: 'Intentar de nuevo',
      
      // Footer
      quickLinks: 'Enlaces Rápidos',
      subjects: 'Materias',
      contactUs: 'Contáctanos',
      teacherGuide: 'Guía del Profesor',
      studentGuide: 'Guía del Estudiante',
      connectingStudents: 'Conectando estudiantes con profesores profesionales en Haití desde 2024',
      allRightsReserved: '© 2025 LesonPaw. Todos los derechos reservados.',
      privacyPolicy: 'Política de Privacidad',
      termsOfService: 'Términos de Servicio',
      cookies: 'Cookies',
      
      // Home Page
      transformingEducation: 'Transformando la Educación',
      inHaiti: 'en Haití',
      buildingBridges: '¡Desbloquea tu potencial con educadores expertos que inspiran. Únete a miles de estudiantes exitosos en la principal plataforma de aprendizaje de Haití. Tu camino hacia la excelencia comienza aquí!',
      getStarted: 'Comenzar Ahora',
      
      // About Page
      ourPurpose: 'Nuestro Propósito',
      empoweringEducation: 'Empoderando la educación a través de la innovación y la accesibilidad',
      forStudents: 'Para Estudiantes',
      forTutors: 'Para Profesores',
      accessToTutors: 'Acceso a tutores calificados en múltiples materias',
      flexibleScheduling: 'Programación flexible según tus necesidades',
      personalizedLearning: 'Experiencia de aprendizaje personalizada',
      progressTracking: 'Seguimiento de progreso y análisis de rendimiento',
      teacherProfile: 'Construye tu perfil y reputación como profesor',
      setSchedule: 'Establece tu propio horario y tarifas',
      teachingResources: 'Acceso a recursos y materiales de enseñanza',
      securePayment: 'Procesamiento seguro de pagos',
      
      // Trust & Security
      trustAndSecurity: 'Confianza y Seguridad',
      yourSafety: 'Tu seguridad y éxito son nuestras principales prioridades',
      verifiedTutors: 'Tutores Verificados',
      support247: 'Soporte 24/7',
      satisfactionGuarantee: 'Garantía de Satisfacción',
      tutorsVerified: 'Todos nuestros tutores pasan por un riguroso proceso de verificación',
      supportAvailable: 'Nuestro equipo de soporte está disponible en cualquier momento para ayudarte',
      qualityEducation: 'Nos comprometemos a proporcionar una educación de alta calidad',
      
      // Subjects
      mathematics: 'Matemáticas',
      sciences: 'Ciencias',
      languages: 'Idiomas',
      history: 'Historia',
      computerScience: 'Informática',
      artsMusic: 'Arte y Música',
      
      // Stats
      studentsHelped: 'Estudiantes Ayudados',
      successfulLearners: 'Aprendices que lograron sus objetivos',
      expertTutors: 'Profesores Expertos',
      qualifiedEducators: 'Educadores Calificados Listos para Ayudar',
      subjectsCovered: 'Materias Cubiertas',
      diverseTopics: 'Amplia Gama de Temas Académicos',
      successRate: 'Tasa de Éxito',
      satisfactionRate: 'Tasa de Satisfacción del Estudiante',
      
      // Values
      ourValues: 'Valores Fundamentales Nuestros',
      principlesGuide: 'Principios que Guían Nuestra Misión para Transformar la Educación',
      integrity: 'Integridad',
      integrityDesc: 'Mantenemos los más altos Estándares de Conducta Profesional',
      innovation: 'Innovación',
      innovationDesc: 'Mejora Continua de Nuestra Plataforma y Métodos',
      growth: 'Crecimiento',
      growthDesc: 'Fomentar el Aprendizaje y Desarrollo Continuo',
      excellence: 'Excelencia',
      excellenceDesc: 'Buscar la Excelencia en Todo lo Que Hacemos',
      
      // Call to Action
      readyToTransform: '¿Listo para Transformar Tu Viaje de Aprendizaje?',
      joinThousands: 'Únete a miles de estudiantes y tutores que ya forman parte de nuestra comunidad en crecimiento',

      // How It Works Section
      howItWorks: '¿Cómo Funciona?',
      searchTeacher: 'Buscar',
      searchTeacherDesc: 'Encuentra el profesor ideal según tus necesidades y ubicación en Haití.',
      connect: 'Conectar',
      connectDesc: 'Programa las clases según tu disponibilidad.',
      learn: 'Aprender',
      learnDesc: 'Recibe instrucción personalizada y alcanza tus objetivos.',
      platformDesc: 'Nuestra plataforma facilita la conexión entre estudiantes y profesores calificados en Haití',
      readyToStart: '¿Listo para comenzar tu viaje de aprendizaje u ofrecer tus servicios de enseñanza?',
      
      // Why Choose Us Section
      whyChooseUs: '¿Por Qué Elegir LessonPaw?',
      committedToEducation: 'Estamos comprometidos a hacer que la educación de calidad sea accesible en todo Haití',
      verifiedTeachers: 'Profesores Verificados',
      verifiedTeachersDesc: 'Todos los profesores son verificados por sus credenciales y experiencia en sus materias.',
      studentCount: '5,000+ Estudiantes',
      studentCountDesc: 'Únete a miles de estudiantes que han encontrado a su profesor ideal.',
      qualityGuarantee: 'Garantía de Calidad',
      qualityGuaranteeDesc: 'Aseguramos una enseñanza de alta calidad o ofrecemos un reemplazo sin costo adicional.',
      safePayments: 'Pagos Seguros',
      safePaymentsDesc: 'Transacciones seguras y protección de pagos para tu tranquilidad.',
      
      // Teacher Section
      meetExperts: 'Conoce a Nuestros Profesores Expertos',
      teacherDesc: 'Descubre nuestra comunidad de profesores calificados, apasionados por la excelencia académica',
      education: 'Educación',
      experience: 'Experiencia',
      subjects: 'Materias',
      languages: 'Idiomas',
      teachingMode: 'Modo de Enseñanza',
      available: 'Disponible',
      viewFullProfile: 'Ver Perfil Completo',
      yearsExperience: 'años de experiencia',
      onlineInPerson: 'En línea y Presencial',
      
      // Success Stories Section
      successStories: 'Nuestras Historias de Éxito',
      successStoriesDesc: 'Descubre cómo nuestra plataforma ha transformado experiencias de aprendizaje y ayudado a estudiantes a alcanzar sus metas',
      viewAllStories: 'Ver Todas las Historias',
      noStories: 'No hay historias de éxito para mostrar por el momento.',
      showLess: 'Mostrar Menos',
      closePreview: 'Cerrar Vista Previa',
      
      // Support Section
      support: 'Soporte',
      supportDesc: '¿Necesitas ayuda? Nuestro equipo de soporte está aquí para ti',
      contactSupport: 'Contactar Soporte',
      supportEmail: 'Soporte por Email',
      supportPhone: 'Soporte Telefónico',
      supportChat: 'Chat en Vivo',
      supportHours: 'Horario de Soporte',
      supportAvailability: 'Soporte Disponible 24/7',
      supportResponse: 'Tiempo de respuesta típico: 2 horas',
      supportTicket: 'Crear Ticket de Soporte',
      supportFAQ: 'Preguntas Frecuentes',
      supportHelp: '¿Necesitas Ayuda?',
      supportTeam: 'Estamos Aquí Para Ayudarte',
      support247: 'Soporte 24/7',
      quickResponse: 'Respuesta Rápida',
      writeMessage: 'Escribe tu mensaje aquí...',
      sendMessage: 'Enviar Mensaje',
      signInToMessage: 'Inicia Sesión para Enviar un Mensaje',
      pleaseLoginMessage: 'Por favor, inicia sesión en tu cuenta para enviarnos un mensaje.',
      
      // What is LesonPaw Section
      whatIsLesonPaw: '¿Qué es',
      connectingStudents: 'Conectando estudiantes con profesores profesionales en Haití desde 2024',
      qualityEducation: 'Educación de Calidad',
      qualityEducationDesc: 'Proporcionamos acceso a educación de alta calidad a través de nuestra red de profesores profesionales verificados.',
      connecting: 'Creando Conexiones',
      connectingDesc: 'Creando conexiones significativas entre estudiantes y profesores para fomentar un ambiente de aprendizaje colaborativo.',
      innovation: 'Innovación Educativa',
      innovationDesc: 'Utilizando tecnología moderna para hacer la educación más accesible y atractiva para todos.',
      lesonPawMission: 'Nuestra misión es transformar la educación en Haití haciendo que el aprendizaje de calidad sea accesible para todos los estudiantes a través de nuestra plataforma innovadora.',

      // Contact Page
      getInTouch: 'Contacta con',
      contactSubtitle: '¡Estamos aquí para ayudar! Envíanos un mensaje y responderemos dentro de las 24 horas hábiles.',
      fullName: 'Nombre Completo',
      nameRequired: 'El nombre es requerido',
      emailRequired: 'El correo electrónico es requerido',
      invalidEmail: 'Dirección de correo electrónico inválida',
      phone: 'Número de Teléfono',
      optional: 'Opcional',
      subject: 'Asunto',
      subjectRequired: 'El asunto es requerido',
      message: 'Mensaje',
      messageRequired: 'El mensaje es requerido',
      messageMinLength: 'El mensaje debe tener al menos 20 caracteres',
      attachments: 'Archivos Adjuntos',
      fileUploadInfo: 'Tamaño máximo: 5MB. Formatos soportados: PDF, DOC, DOCX, JPG, PNG',
      verifyCaptcha: 'Verificar Captcha',
      enterCaptcha: 'Ingrese el texto del captcha',
      captchaValidated: '¡Captcha Validado!',
      captchaRequired: 'Captcha Requerido',
      pleaseVerifyCaptcha: 'Por favor, verifica el captcha antes de enviar',
      sending: 'Enviando...',
      responseTime: 'Te responderemos dentro de las 24 horas hábiles.',
      submissionFailed: 'Submission Failed',
      tryAlternativeContact: 'Por favor, intenta más tarde o usa métodos alternativos de contacto.',
      businessHours: 'Horario de Atención',
      mondayFriday: 'Lunes - Viernes',
      saturday: 'Sábado',
      sunday: 'Domingo',
      closed: 'Cerrado',
      timeZone: 'Todos los horarios están en Hora del Este (ET)',
      contactInfo: 'Informaciones de Contacto',
      address: 'Dirección',
      connectWithUs: 'Conéctate con Nosotros',
      ourLocation: 'Nuestra Ubicación',
      getDirections: 'Obtenir Direksyon',

      // Dashboard Menu
      manageProfile: 'Gestionar Perfil',
      myBookings: 'Mis Reservas',
      joinAsTeacher: 'Unirse como Profesor',
      postJob: 'Publicar Trabajo',
      myPosts: 'Mis Publicaciones',
      availableJobs: 'Trabajos Disponib',
      manageServices: 'Gestionar Servicios',
      manageUsers: 'Gestionar Usuarios',
      allTutors: 'Todos los Tutores',
      showMessages: 'Mostrar Mensajes',
      addTutor: 'Añadir Tutor',
      applications: 'Solicitudes',
      payments: 'Pagos',
      analytics: 'Análisis',
      students: 'Estudiantes',
      allJobs: 'Todos los Trabajos',
      allServices: 'Todos los Servicios',
      story: 'Historia',
      manageStory: 'Jere Istwa',
      addBlog: 'Añadir Blog',
      editBlog: 'Editar Blog',
      confirmation: 'Confirmaciones',
      menu: 'Menú',

      // Find Teacher Guide
      findPerfectTeacher: 'Encuentra Tu Profesor Perfecto',
      findTeacherDesc: 'Descubre educadores expertos que te guiarán hacia la excelencia académique y el crecimiento personal',
      smartSearch: 'Búsqueda Inteligente',
      smartSearchDesc: 'Nuestro sistema de coincidencia inteligente te ayuda a encontrar el profesor perfecto según tus objetivos de aprendizaje, materias preferidas y horario.',
      expertVerification: 'Verificación de Expertos',
      expertVerificationDesc: 'Cada profesor pasa por un riguroso proceso de verificación. Ve perfiles detallados con credenciales verificadas, experiencia y reseñas de estudiantes.',
      flexibleLearning: 'Aprendizaje Flexible',
      flexibleLearningDesc: 'Elige entre sesiones en línea o presenciales. Programa lecciones que se adapten a tu estilo de vida con nuestro sistema de reservas fácil de usar.',
      personalizedExperience: 'Expérience Personalizada',
      personalizedExperienceDesc: 'Disfruta de planes de aprendizaje personalizados, seguimiento del progreso y apoyo continuo durante tu viaje educativo.',
      verifiedTeachers: 'Profesores Verificados',
      verifiedTeachersCount: 'Profesores Verificados',
      subjectsOffered: 'Materias Ofrecidas',
      studentSatisfaction: 'Satisfacción del Estudiante',
      learningJourneyStart: 'Tu Viaje de Aprendizaje Comienza Aquí',
      whyStudentsChooseUs: '¿Por Qué los Estudiantes Nos Eligen?',
      expertTeachers: 'Profesores Expertos',
      expertTeachersDesc: 'Aprende de profesionales certificados con trayectoria comprobada',
      modernLearningTools: 'Herramientas de Aprendizaje Modernas',
      modernLearningToolsDesc: 'Accede a recursos educativos y tecnología de vanguardia',
      communitySupport: 'Apoyo Comunitario',
      communitySupportDesc: 'Únete a una vibrante comunidad de aprendizaje de estudiantes y educadores',
      startLearningToday: 'Comienza a Aprender Hoy',
      learnMoreAboutUs: 'Aprende Más Sobre Nosotros',

      // Become Teacher Guide
      becomeExpertTeacher: 'Conviértete en un Profesor Experto',
      becomeTeacherDesc: 'Comparte tu conocimiento, inspirez los estudiantes y construisez una carrera docente gratificante en nuestra plataforma',
      teacherProfile: 'Construisez Votre Profil',
      buildProfileDesc: 'Créez un profil d\'enseignement convincente qui montre votre expertise, votre méthodologie d\'enseignement et vos réalisations professionnelles.',
      qualityVerification: 'Vérification de Calité',
      qualityVerificationDesc: 'Pwosesis verifikasyon rigoureux nou an asire wo nivo estanda ansèyman. Soumèt referans ak sètifikasyon ou yo.',
      customizeTeaching: 'Pèsonalize Ansèyman Ou',
      customizeTeachingDesc: 'Fikse preferans ansèyman ou, pri, ak disponibilite. Chwazi ant opsyon ansèyman sou entènèt ak an pèsòn.',
      startJourney: 'Kòmanse Pakou Ou',
      startJourneyDesc: 'Konekte ak elèv yo, bay leson enteresan, epi devlope biznis ansèyman ou sou platfòm nou an.',
      professionalGrowth: 'Kwasans Pwofesyonèl',
      professionalGrowthDesc: 'Jwenn aksè a resous devlopman pwofesyonèl epi bati pòtfolyo ansèyman ou',
      teachingTools: 'Zouti Ansèyman',
      teachingToolsDesc: 'Itilize platfòm ak resous ansèyman avanse nou yo',
      careerDevelopment: 'Devlopman Karyè',
      careerDevelopmentDesc: 'Elaji pòte ou epi devlope karyè ansèyman ou',
      flexibleSchedule: 'Orè Fleksib',
      flexibleScheduleDesc: 'Travay selon kondisyon pa ou',
      platformSupport: 'Sipò Platfòm',
      platformSupportDesc: 'Toujou la pou ede ou',
      earningPotential: 'Potansyèl Revni',
      earningPotentialDesc: 'Fikse pwòp pri ou',
      teachingJourneyBegins: 'Pakou Ansèyman Ou Kòmanse Isit',
      teachingBenefits: 'Avantaj Ansèyman Ak Nou',
      readyToTeach: 'Ou Pare Pou Kòmanse Pakou Ansèyman Ou?',
      joinTeacherCommunity: 'Antre nan kominote edikatè pasyone nou an epi fè yon diferans nan lavi elèv yo',
      applyAsTeacher: 'Aplike Kòm Pwofesè',
      learnMoreTeaching: 'Learn More About Teaching',

      // Blog Page
      discoverKnowledge: 'Descubre',
      insights: 'Perspectivas',
      blogDescription: 'Explora artículos interesantes, consejos de expertos e historias inspiradoras de nuestra comunidad de educadores y estudiantes.',
      searchBlogsPlaceholder: 'Buscar artículos por título, categoría o contenido...',
      popular: 'Popular',
      teachingTips: 'Consejos de Enseñanza',
      studyGuides: 'Guías de Estudio',
      learningResources: 'Recursos de Aprendizaje',
      studentSuccess: 'Éxito Estudiantil',
      allCategories: 'Todas las Categorías',
      noPostsFound: 'No se encontraron publicaciones',
      adjustSearchOrCategory: 'Intenta ajustar tu búsqueda o filtro de categoría',
      readMore: 'Leer Más',
      tags: 'Etiquetas',
      education: 'Educación',
      technology: 'Tecnología',
      learning: 'Aprendizaje',
      teaching: 'Enseñanza',
      students: 'Estudiantes',
      tips: 'Consejos',
      recentPosts: 'Publicaciones Recientes',
      failedToLoadBlogs: 'Error al cargar los blogs',
      errorLoadingBlogs: 'Error al Cargar los Blogs',
      tryAgainLater: 'Por favor, inténtalo de nuevo más tarde',
      readTime: 'Tiempo de lectura',
      author: 'Autor',
      relatedTopics: 'Temas Relacionados',

      // Our Journey Section
      ourJourney: 'Nuestro Viaje',
      journeySubtitle: 'Descubre cómo hemos evolucionado para convertirnos en la principal plataforma educativa en Haití',
      ideaLaunch: 'Lanzamiento de la Idea',
      ideaLaunchDesc: 'LesonPaw fue fundada con la visión de transformar la educación en Haití',
      prototypeTitle: 'Lanzamiento del Primer Prototipo',
      prototypeDesc: 'Alcanzamos nuestro primer hito de ayudar a los estudiantes',
      webLaunchTitle: 'Lanzamiento de la Aplicación Web',
      webLaunchDesc: 'Expandimos nuestro alcance con una aplicación web dedicada',
      recognitionTitle: 'Reconocimiento Nacional',
      recognitionDesc: 'Reconocida como plataforma educativa líder en Haití',

      // Meet Team Section
      meetTeam: 'Conoce a Nuestro Equipo',
      teamSubtitle: 'Profesionales apasionados trabajando para transformar la educación en Haití',
      founderRole: 'Fundador y CEO',
      founderBio: 'Apasionado por hacer la educación accesible a todos los estudiantes haitianos',
      educationRole: 'Directora de Educación',
      educationBio: 'Experta en desarrollo curricular con más de 10 años de experiencia en enseñanza',
      techRole: 'Directeur Technique',
      techBio: 'Asure des expériences d\'apprentissage fluides grâce à la technologie',
      achievements: 'Réalisations',
      yearsInEdTech: '10+ años en EdTech',
      harvardGrad: 'Graduado de Harvard Business School',
      educationAward: 'Premio a la Innovación Educativa 2023',
      formerProf: 'Ex Profesor Universitario',
      publishedAuthor: 'Otè Pibliye nan Edikasyon',
      teachingAward: 'Premio Nacional a la Excelencia en Enseñanza',
      yearsInTech: '15+ ane nan Teknoloji',
      mitGrad: 'MIT nan Enfòmatik',
      techPatents: 'Plizyè Brevet Teknolojik'
    }
  },
  fr: {
    name: 'Français',
    flag: '🇫🇷',
    translations: {
      // Navigation & Common
      home: 'Accueil',
      about: 'À Propos de Nous',
      blog: 'Ressources',
      dashboard: 'Tableau de Bord',
      login: 'Connexion',
      signup: 'Inscription',
      resources: 'Ressources',
      findTeacher: 'Trouver un Professeur',
      becomeTeacher: 'Devenir Professeur',
      logout: 'Déconnexion',
      contact: 'Contact',
      
      // Auth Forms
      welcomeBack: 'Bon Retour!',
      continueJourney: 'Connectez-vous pour continuer votre parcours avec LesonPaw',
      email: 'Email',
      password: 'Mot de passe',
      forgotPassword: 'Mot de passe oublié?',
      enterEmail: 'Entrez votre email',
      enterPassword: 'Entrez votre mot de passe',
      validate: 'Valider',
      captchaText: 'Entrez le texte du captcha',
      newToSite: 'Nouveau sur LesonPaw?',
      createAccount: 'Créer un compte',
      successLogin: 'Connexion réussie!',
      failedLogin: 'Échec de la connexion',
      tryAgain: 'Réessayer',
      
      // Footer
      quickLinks: 'Liens Rapides',
      subjects: 'Matières',
      contactUs: 'Contactez-nous',
      teacherGuide: 'Guide du Professeur',
      studentGuide: "Guide de l'Étudiant",
      connectingStudents: 'Connecter les étudiants avec des professeurs professionnels à travers Haïti depuis 2024',
      allRightsReserved: '© 2025 LesonPaw. Tous droits réservés.',
      privacyPolicy: 'Politique de Confidentialité',
      termsOfService: "Conditions d'Utilisation",
      cookies: 'Cookies',
      
      // Home Page
      transformingEducation: "Transformer l'Éducation",
      inHaiti: 'en Haïti',
      buildingBridges: 'Libérez votre potentiel avec des éducateurs experts qui inspirent. Rejoignez des milliers d\'étudiants qui réussissent sur la première plateforme d\'apprentissage d\'Haïti. Votre chemin vers l\'excellence commence ici !',
      getStarted: 'Commencer Maintenant',
      
      // About Page
      ourPurpose: 'Notre Mission',
      empoweringEducation: 'Bay pouvwa edikasyon atravè inovasyon ak aksè',
      forStudents: 'Pour les Étudiants',
      forTutors: 'Pou les Professeurs',
      accessToTutors: 'Aksè a pwofesè kalifye nan plizyè matyè',
      flexibleScheduling: 'Orè fleksib selon bezwen ou',
      personalizedLearning: 'Eksperyans aprantisaj pèsonalize',
      progressTracking: 'Swivi pwogrè ak analiz pèfòmans',
      teacherProfile: 'Bati pwofil ou ak reputasyon ou kòm pwofesè',
      setSchedule: 'Fikse pwòp orè ak pri ou',
      teachingResources: 'Aksè a resous ak materyèl ansèyman',
      securePayment: 'Tretman peman sekirize',
      
      // Trust & Security
      trustAndSecurity: 'Confiance et Sécurité',
      yourSafety: 'Votre sécurité et votre satisfaction sont nos priorités absolues',
      verifiedTutors: 'Tuteurs Vérifiés',
      tutorsVerified: 'Tous nos tuteurs passent par un processus de vérification rigoureux',
      support247: 'Support 24/7',
      supportAvailable: 'Notre équipe de support est disponible à tout moment pour vous aider',
      satisfactionGuarantee: 'Garantie de Satisfaction',
      qualityEducation: 'Nous nous engageons à fournir une éducation de haute qualité',
      
      // Subjects
      mathematics: 'Matematik',
      sciences: 'Syans',
      languages: 'Lang',
      history: 'Istwa',
      computerScience: 'Enfòmatik',
      artsMusic: 'Art ak Mizik',
      
      // Stats
      studentsHelped: 'Elèv ki Jwenn Èd',
      successfulLearners: 'Apranti ki reyisi objektif yo',
      expertTutors: 'Pwofesè Ekspè',
      qualifiedEducators: 'Edikatè kalifye ki pare pou ede',
      subjectsCovered: 'Matyè ki Kouvri',
      diverseTopics: 'Divès sijè akademik',
      successRate: 'To Siksè',
      satisfactionRate: 'To satisfaksyon elèv yo',
      
      // Values
      ourValues: 'Valè Fondamantal Nou yo',
      principlesGuide: 'Prensip ki gide misyon nou pou transfòme edikasyon',
      integrity: 'Entegrite',
      integrityDesc: 'Nou kenbe pi wo nivo konduit pwofesyonèl',
      innovation: 'Aprantisaj Inovatif',
      innovationDesc: 'Itilize teknoloji pou rann edikasyon pi aksesib ak pi angajan pou tout moun.',
      growth: 'Kwasans',
      growthDesc: 'Ankouraje aprantisaj ak devlopman kontinyèl',
      excellence: 'Ekselans',
      excellenceDesc: 'Vize pi bon nan tout sa nou fè',
      
      // Call to Action
      readyToTransform: 'Ou Pare pou Transfòme Pakou Aprantisaj Ou?',
      joinThousands: 'Jwenn ak milye elèv ak pwofesè ki deja fè pati kominote nou an k ap grandi',

      // How It Works Section
      howItWorks: 'Comment ça Marche',
      searchTeacher: 'Rechercher',
      searchTeacherDesc: 'Trouvez le professeur idéal en fonction de vos besoins et de votre localisation en Haïti.',
      connect: 'Se Connecter',
      connectDesc: 'Planifiez vos cours selon vos disponibilités.',
      learn: 'Apprendre',
      learnDesc: 'Recevez un enseignement personnalisé et atteignez vos objectifs.',
      platformDesc: 'Notre plateforme facilite la connexion entre les étudiants et les professeurs qualifiés en Haïti',
      readyToStart: 'Prêt à commencer votre parcours d\'apprentissage ou à proposer vos services d\'enseignement ?',
      
      // Why Choose Us Section
      whyChooseUs: 'Pourquoi Choisir LessonPaw',
      committedToEducation: 'Nous nous engageons à rendre l\'éducation de qualité accessible dans toute Haïti',
      verifiedTeachers: 'Professeurs Vérifiés',
      verifiedTeachersDesc: 'Tous nos professeurs sont vérifiés pour leurs qualifications et leur expertise dans leurs matières.',
      studentCount: '5,000+ Étudiants',
      studentCountDesc: 'Rejoignez des milliers d\'étudiants qui ont trouvé leur professeur idéal.',
      qualityGuarantee: 'Garantie de Qualité',
      qualityGuaranteeDesc: 'Nous garantissons un enseignement de haute qualité ou proposons un remplacement sans frais supplémentaires.',
      safePayments: 'Paiements Sécurisés',
      safePaymentsDesc: 'Transactions sécurisées et protection des paiements pour votre tranquillité d\'esprit.',
      
      // Teacher Section
      meetExperts: 'Rencontrez Nos Professeurs Experts',
      teacherDesc: 'Découvrez notre communauté d\'enseignants qualifiés, passionnés par l\'excellence académique',
      education: 'Formation',
      experience: 'Expérience',
      subjects: 'Matières',
      languages: 'Langues',
      teachingMode: 'Mode d\'Enseignement',
      available: 'Disponible',
      viewFullProfile: 'Voir le Profil Complet',
      yearsExperience: 'ans d\'expérience',
      onlineInPerson: 'En ligne & En personne',
      
      // Success Stories Section
      successStories: 'Nos Histoires de Réussite',
      successStoriesDesc: 'Découvrez comment notre plateforme a transformé les expériences d\'apprentissage et aidé les étudiants à atteindre leurs objectifs',
      viewAllStories: 'Voir Toutes les Histoires',
      noStories: 'Aucune histoire de réussite à afficher pour le moment.',
      showLess: 'Voir Moins',
      closePreview: 'Fermer l\'Aperçu',
      
      // Support Section
      support: 'Support',
      supportDesc: 'Besoin d\'aide ? Notre équipe de support est là pour vous',
      contactSupport: 'Contacter le Support',
      supportEmail: 'Support par Email',
      supportPhone: 'Support Téléphonique',
      supportChat: 'Chat en Direct',
      supportHours: 'Heures de Support',
      supportAvailability: 'Support Disponible 24/7',
      supportResponse: 'Temps de réponse typique : 2 heures',
      supportTicket: 'Créer un Ticket de Support',
      supportFAQ: 'FAQ',
      supportHelp: 'Besoin d\'Aide ?',
      supportTeam: 'Nous Sommes Là Pour Vous Aider',
      support247: 'Support 24/7',
      quickResponse: 'Réponse Rapide',
      writeMessage: 'Écrivez votre message ici...',
      sendMessage: 'Envoyer le Message',
      signInToMessage: 'Connectez-vous pour Envoyer un Message',
      pleaseLoginMessage: 'Veuillez vous connecter à votre compte pour nous envoyer un message.',
      
      // What is LesonPaw Section
      whatIsLesonPaw: "Qu'est-ce que",
      connectingStudents: "Connecter les étudiants avec des professeurs professionnels à travers Haïti depuis 2024",
      qualityEducation: "Éducation de Qualité",
      qualityEducationDesc: "Nous fournissons un accès à une éducation de haute qualité grâce à notre réseau de professeurs professionnels vérifiés.",
      connecting: "Créer des Connexions",
      connectingDesc: "Créer des connexions significatives entre les étudiants et les professeurs pour favoriser un environnement d'apprentissage collaboratif.",
      innovation: "Innovation Pédagogique",
      innovationDesc: "Utilisation de technologies modernes pour rendre l'éducation plus accessible et engageante pour tous.",
      lesonPawMission: "Notre mission est de transformer l'éducation en Haïti en rendant l'apprentissage de qualité accessible à tous les étudiants grâce à notre plateforme innovante.",

      // Contact Page
      getInTouch: 'Contactez',
      contactSubtitle: 'Nous la pour ede w! Voye nou yon mesaj epi nou ap reponn nan 24 èdtan.',
      fullName: 'Non Konplè',
      nameRequired: 'Non an obligatwa',
      emailRequired: 'Imèl la obligatwa',
      invalidEmail: 'Adrès imèl la pa valid',
      phone: 'Nimewo Telefòn',
      optional: 'Opsyonèl',
      subject: 'Sijè',
      subjectRequired: 'Sijè a obligatwa',
      message: 'Mesaj',
      messageRequired: 'Mesaj la obligatwa',
      messageMinLength: 'Mesaj la dwe gen omwen 20 karaktè',
      attachments: 'Dokiman',
      fileUploadInfo: 'Gwosè maksimòm: 5MB. Fòma ki aksepte: PDF, DOC, DOCX, JPG, PNG',
      verifyCaptcha: 'Verifye Captcha',
      enterCaptcha: 'Antre tèks captcha a',
      captchaValidated: 'Captcha Verifye!',
      captchaRequired: 'Captcha Obligatwa',
      pleaseVerifyCaptcha: 'Tanpri verifye captcha a anvan ou soumèt',
      sending: 'Ap voye...',
      responseTime: 'Nou ap reponn ou nan 24 èdtan.',
      submissionFailed: 'Echèk nan Voye',
      tryAlternativeContact: 'Tanpri eseye ankò pita',
      businessHours: 'Orè Biznis',
      mondayFriday: 'Lendi - Vandredi',
      saturday: 'Samdi',
      sunday: 'Dimanch',
      closed: 'Fèmen',
      timeZone: 'Tout lè yo se nan Lè Lès (ET)',
      contactInfo: 'Enfòmasyon Kontak',
      address: 'Adrès',
      connectWithUs: 'Konekte ak Nou',
      ourLocation: 'Lokalizasyon Nou',
      getDirections: 'Jwenn Direksyon',

      // Dashboard Menu
      manageProfile: 'Jere Pwofil',
      myBookings: 'Rezèvasyon Mwen',
      joinAsTeacher: 'Vin yon Pwofesè',
      postJob: 'Poste Travay',
      myPosts: 'Piblikasyon Mwen',
      availableJobs: 'Travay Disponib',
      manageServices: 'Jere Sèvis',
      manageUsers: 'Jere Itilizatè',
      allTutors: 'Tout Pwofesè',
      showMessages: 'Montre Mesaj',
      addTutor: 'Ajoute Pwofesè',
      applications: 'Aplikasyon',
      payments: 'Peman',
      analytics: 'Analiz',
      students: 'Elèv',
      allJobs: 'Tout Travay',
      allServices: 'Tout Sèvis',
      story: 'Istwa',
      manageStory: 'Jere Istwa',
      addBlog: 'Ajoute Blog',
      editBlog: 'Modifye Blog',
      confirmation: 'Konfimasyon yo',
      menu: 'Meni',

      // Find Teacher Guide
      findPerfectTeacher: 'Jwenn Pwofesè Pafè Ou',
      findTeacherDesc: 'Dekouvri edikatè ekspè ki pral gide ou nan ekselans akademik ak kwasans pèsonèl',
      smartSearch: 'Rechèch Entèlijan',
      smartSearchDesc: 'Sistèm match entèlijan nou an ede ou jwenn pwofesè pafè a selon objektif aprantisaj ou, matyè ou prefere, ak orè ou.',
      expertVerification: 'Verifikasyon Ekspè',
      expertVerificationDesc: 'Chak pwofesè pase nan yon pwosesis verifikasyon rigoureux. Gade pwofil detaye ak referans verifye, eksperyans, ak opinyon elèv yo.',
      flexibleLearning: 'Aprantisaj Fleksib',
      flexibleLearningDesc: 'Chwazi ant sesyon sou entènèt oswa an pèsòn. Planifye leson ki adapte ak style lavi ou ak sistèm rezèvasyon fasil nou an.',
      personalizedExperience: 'Eksperyans Pèsonalize',
      personalizedExperienceDesc: 'Jwi plan aprantisaj pèsonalize, swivi pwogrè, ak sipò kontinyèl pandan tout pakou edikasyonèl ou.',
      verifiedTeachers: 'Pwofesè Verifye',
      verifiedTeachersCount: 'Pwofesè Verifye',
      subjectsOffered: 'Matyè Disponib',
      studentSatisfaction: 'Satisfaksyon Elèv',
      learningJourneyStart: 'Pakou Aprantisaj Ou Kòmanse Isit',
      whyStudentsChooseUs: 'Poukisa Elèv Yo Chwazi Nou',
      expertTeachers: 'Pwofesè Ekspè',
      expertTeachersDesc: 'Aprann ak pwofesyonèl sètifye ki gen eksperyans pwouve',
      modernLearningTools: 'Zouti Aprantisaj Modèn',
      modernLearningToolsDesc: 'Aksè a resous edikasyonèl ak teknoloji dènye kri',
      communitySupport: 'Sipò Kominote',
      communitySupportDesc: 'Antre nan yon kominote aprantisaj dinamik elèv ak edikatè',
      startLearningToday: 'Kòmanse Aprann Jodi a',
      learnMoreAboutUs: 'Aprann Plis Sou Nou',

      // Become Teacher Guide
      becomeExpertTeacher: 'Devenez un Professeur Expert',
      becomeTeacherDesc: 'Partagez vos connaissances, inspirez les étudiants et construisez une carrière enrichissante dans l\'enseignement sur notre plateforme',
      teacherProfile: 'Construisez Votre Profil',
      buildProfileDesc: 'Créez un profil d\'enseignement convaincant qui montre votre expertise, votre méthodologie d\'enseignement et vos réalisations professionnelles.',
      qualityVerification: 'Vérification de Qualité',
      qualityVerificationDesc: 'Notre processus de vérification rigoureux assure des standards d\'enseignement élevés. Soumettez vos références et certifications.',
      customizeTeaching: 'Personnalisez Votre Enseignement',
      customizeTeachingDesc: 'Définissez vos préférences d\'enseignement, vos tarifs et votre disponibilité. Choisissez entre l\'enseignement en ligne et en personne.',
      startJourney: 'Commencez Votre Parcours',
      startJourneyDesc: 'Connectez-vous avec des étudiants, donnez des cours intéressants et développez votre activité d\'enseignement sur notre plateforme.',
      professionalGrowth: 'Croissance Professionnelle',
      professionalGrowthDesc: 'Accédez à des ressources de développement professionnel et construisez votre portfolio d\'enseignement',
      teachingTools: 'Outils d\'Enseignement',
      teachingToolsDesc: 'Utilisez notre plateforme et nos ressources d\'enseignement avancées',
      careerDevelopment: 'Développement de Carrière',
      careerDevelopmentDesc: 'Élargissez votre portée et développez votre carrière d\'enseignant',
      flexibleSchedule: 'Horaires Flexibles',
      flexibleScheduleDesc: 'Travaillez selon vos conditions',
      platformSupport: 'Support de la Plateforme',
      platformSupportDesc: 'Toujours là pour vous aider',
      earningPotential: 'Potentiel de Revenus',
      earningPotentialDesc: 'Fixez vos propres tarifs',
      teachingJourneyBegins: 'Votre Parcours d\'Enseignement Commence Ici',
      teachingBenefits: 'Avantages de l\'Enseignement Avec Nous',
      readyToTeach: 'Prêt à Commencer Votre Parcours d\'Enseignement ?',
      joinTeacherCommunity: 'Rejoignez notre communauté d\'éducateurs passionnés et faites une différence dans la vie des étudiants',
      applyAsTeacher: 'Postuler Comme Professeur',
      learnMoreTeaching: 'En Savoir Plus sur l\'Enseignement',

      // Blog Page
      discoverKnowledge: 'Découvrez',
      insights: 'Perspectives',
      blogDescription: 'Explorez des articles intéressants, des conseils d\'experts et des histoires inspirantes provenant de notre communauté d\'éducateurs et d\'apprenants.',
      searchBlogsPlaceholder: 'Rechercher des articles par titre, catégorie ou contenu...',
      popular: 'Populaire',
      teachingTips: 'Conseils d\'Enseignement',
      studyGuides: 'Guides d\'Étude',
      learningResources: 'Ressources d\'Apprentissage',
      studentSuccess: 'Réussites des Étudiants',
      allCategories: 'Toutes les Catégories',
      noPostsFound: 'Aucun article trouvé',
      adjustSearchOrCategory: 'Essayez d\'ajuster votre recherche ou votre filtre de catégorie',
      readMore: 'Lire la suite',
      tags: 'Étiquettes',
      education: 'Éducation',
      technology: 'Technologie',
      learning: 'Apprentissage',
      teaching: 'Enseignement',
      students: 'Étudiants',
      tips: 'Conseils',
      recentPosts: 'Articles récents',
      failedToLoadBlogs: 'Échec du chargement des articles',
      errorLoadingBlogs: 'Erreur de chargement des articles',
      tryAgainLater: 'Veuillez réessayer plus tard',
      readTime: 'Temps de lecture',
      author: 'Auteur',
      relatedTopics: 'Sujets Connexes',

      // Our Journey Section
      ourJourney: 'Notre Parcours',
      journeySubtitle: 'Découvrez comment nous avons évolué pour devenir la principale plateforme éducative en Haïti',
      ideaLaunch: 'Lancement de l\'Idée',
      ideaLaunchDesc: 'LesonPaw a été fondé avec la vision de transformer l\'éducation en Haïti',
      prototypeTitle: 'Lancement du Premier Prototype',
      prototypeDesc: 'Nous avons atteint notre premier objectif d\'aide aux étudiants',
      webLaunchTitle: 'Lancement de l\'Application Web',
      webLaunchDesc: 'Nous avons étendu notre portée avec une application Web dédiée',
      recognitionTitle: 'Reconnaissance Nationale',
      recognitionDesc: 'Reconnu comme plateforme éducative leader en Haïti',

      // Meet Team Section
      meetTeam: 'Rencontrez Notre Équipe',
      teamSubtitle: 'Des professionnels passionnés qui travaillent pour transformer l\'éducation en Haïti',
      founderRole: 'Fondateur & PDG',
      founderBio: 'Passionné par l\'accessibilité de l\'éducation pour tous les étudiants haïtiens',
      educationRole: 'Directrice de l\'Éducation',
      educationBio: 'Experte en développement de programmes avec plus de 10 ans d\'expérience dans l\'enseignement',
      techRole: 'Directeur Technique',
      techBio: 'Assure des expériences d\'apprentissage fluides grâce à la technologie',
      achievements: 'Réalisations',
      yearsInEdTech: '10+ ans dans l\'EdTech',
      harvardGrad: 'Diplômé de Harvard Business School',
      educationAward: 'Prix de l\'Innovation en Éducation 2023',
      formerProf: 'Ancien Professeur d\'Université',
      publishedAuthor: 'Auteur Publié en Éducation',
      teachingAward: 'Prix National d\'Excellence en Enseignement',
      yearsInTech: '15+ ans dans la Tech',
      mitGrad: 'MIT en Informatique',
      techPatents: 'Multiples Brevets Technologiques',

      // Find Teacher Guide Page
      findPerfectTeacher: 'Trouvez Votre Professeur Idéal',
      findTeacherDesc: 'Découvrez des éducateurs experts qui vous guideront vers l\'excellence académique et la croissance personnelle',
      verifiedTeachers: 'Professeurs Vérifiés',
      subjectsOffered: 'Matières Proposées',
      studentSatisfaction: 'Satisfaction des Étudiants',
      learningJourneyStart: 'Votre Parcours d\'Apprentissage Commence Ici',
      smartSearch: 'Recherche Intelligente',
      smartSearchDesc: 'Notre système de mise en relation intelligent vous aide à trouver le professeur parfait selon vos objectifs d\'apprentissage, vos matières préférées et votre emploi du temps.',
      expertVerification: 'Vérification des Experts',
      expertVerificationDesc: 'Chaque professeur passe par un processus de vérification rigoureux. Consultez les profils détaillés avec références vérifiées, expérience et avis des étudiants.',
      flexibleLearning: 'Apprentissage Flexible',
      flexibleLearningDesc: 'Choisissez entre des sessions en ligne ou en personne. Planifiez des leçons qui s\'adaptent à votre style de vie avec notre système de réservation facile.',
      personalizedExperience: 'Expérience Personnalisée',
      personalizedExperienceDesc: 'Profitez de plans d\'apprentissage personnalisés, du suivi des progrès et d\'un soutien continu tout au long de votre parcours éducatif.',
      whyStudentsChooseUs: 'Pourquoi les Étudiants Nous Choisissent',
      expertTeachers: 'Professeurs Experts',
      expertTeachersDesc: 'Apprenez avec des professionnels certifiés ayant fait leurs preuves',
      modernLearningTools: 'Outils d\'Apprentissage Modernes',
      modernLearningToolsDesc: 'Accédez à des ressources éducatives et une technologie de pointe',
      communitySupport: 'Support Communautaire',
      communitySupportDesc: 'Rejoignez une communauté d\'apprentissage dynamique d\'étudiants et d\'éducateurs',
      readyToTransform: 'Prêt à Transformer Votre Parcours d\'Apprentissage ?',
      joinThousands: 'Rejoignez des milliers d\'étudiants qui ont déjà trouvé leur professeur idéal',
      startLearningToday: 'Commencez à Apprendre',
      learnMoreAboutUs: 'En Savoir Plus',

      // Why Choose LessonPaw Section
      whyChoose: 'Pourquoi Choisir',
      ourCommitment: 'Notre engagement à offrir une éducation de qualité accessible à travers Haïti',
      verifiedProfessors: 'Professeurs Vérifiés',
      allProfessorsVerified: 'Tous nos professeurs sont vérifiés pour leurs qualifications et leur expertise',
      studentCount: '5,000+ Étudiants',
      studentCountDesc: 'Plus de cinq mille étudiants qui font déjà confiance à nos professeurs',
      qualityGuarantee: 'Garantie Qualité',
      qualityGuaranteeDesc: 'Nous garantissons une expérience d\'apprentissage de haute qualité sans risque',
      securePayment: 'Paiement Sécurisé',
      securePaymentDesc: 'Options de paiement sécurisées via mobile money disponibles dans toute Haïti',
      
      // Stats
      professorsVerified: '1,200+ Professeurs Vérifiés',
      lessonsCompleted: '25,000+ Cours Complétés',
      satisfactionRate: '95% Taux de Satisfaction',
      citiesInHaiti: '32 Villes en Haïti',
      
      // CTA Button
      joinCommunity: 'Rejoindre Notre Communauté'
    }
  },
  ht: {
    name: 'Kreyòl',
    flag: '🇭🇹',
    translations: {
      // Navigation & Common
      home: 'Akèy',
      about: 'Apropo de Nou',
      blog: 'Resous',
      dashboard: 'Tablo de Bò',
      login: 'Konekte',
      signup: 'Enskri',
      resources: 'Resous',
      findTeacher: 'Jwenn yon Pwofesè',
      becomeTeacher: 'Vin yon Pwofesè',
      logout: 'Dekonekte',
      contact: 'Kontak',
      
      // Auth Forms
      welcomeBack: 'Byenveni Ankò!',
      continueJourney: 'Konekte pou kontinye aprantisaj ou ak LesonPaw',
      email: 'Imèl',
      password: 'Modpas',
      forgotPassword: 'Ou bliye modpas ou?',
      enterEmail: 'Antre imèl ou',
      enterPassword: 'Antre modpas ou',
      validate: 'Valide',
      captchaText: 'Antre tèks captcha a',
      newToSite: 'Ou nouvo sou LesonPaw?',
      createAccount: 'Kreye yon kont',
      successLogin: 'Koneksyon reyisi!',
      failedLogin: 'Koneksyon echwe',
      tryAgain: 'Eseye ankò',
      
      // Footer
      quickLinks: 'Lyen Rapid',
      subjects: 'Matyè',
      contactUs: 'Kontakte Nou',
      teacherGuide: 'Gid Pwofesè',
      studentGuide: 'Gid Elèv',
      connectingStudents: 'Konekte elèv yo ak pwofesè pwofesyonèl atravè Ayiti depi 2023',
      allRightsReserved: '© 2025 LesonPaw. Tout dwa rezève.',
      privacyPolicy: 'Politik Konfidansyalite',
      termsOfService: 'Kondisyon Sèvis',
      cookies: 'Cookies',
      
      // Home Page
      transformingEducation: 'Transfòme Edikasyon',
      inHaiti: 'an Ayiti',
      buildingBridges: 'Debloke potansyèl ou ak pwofesè ekspè ki enspire. Jwenn ak plizyè milye elèv ki gen siksè sou pi bon platfòm aprantisaj Ayiti a. Chemen ou pou ekselans la kòmanse isit la!',
      getStarted: 'Kòmanse Kounye a',
      
      // About Page
      ourPurpose: 'Misyon Nou',
      empoweringEducation: 'Bay pouvwa edikasyon atravè inovasyon ak aksè',
      forStudents: 'Pou Elèv yo',
      forTutors: 'Pou Pwofesè yo',
      accessToTutors: 'Aksè a pwofesè kalifye nan plizyè matyè',
      flexibleScheduling: 'Orè fleksib selon bezwen ou',
      personalizedLearning: 'Eksperyans aprantisaj pèsonalize',
      progressTracking: 'Swivi pwogrè ak analiz pèfòmans',
      teacherProfile: 'Bati pwofil ou ak reputasyon ou kòm pwofesè',
      setSchedule: 'Fikse pwòp orè ak pri ou',
      teachingResources: 'Aksè a resous ak materyèl ansèyman',
      securePayment: 'Tretman peman sekirize',
      
      // Trust & Security
      trustAndSecurity: 'Konfyans ak Sekirite',
      yourSafety: 'Sekirite ou ak siksè ou se priyorite nou yo',
      verifiedTutors: 'Pwofesè Verifye',
      tutorsVerified: 'Tout pwofesè nou yo pase nan yon pwosesis verifikasyon ki estrik',
      support247: 'Sipò 24/7',
      supportAvailable: 'Ekip sipò nou an disponib nenpòt ki lè pou ede w',
      satisfactionGuarantee: 'Garanti Satisfaksyon',
      qualityEducation: 'Nou angaje nou pou bay edikasyon kalite siperyè',
      
      // Subjects
      mathematics: 'Matematik',
      sciences: 'Syans',
      languages: 'Lang',
      history: 'Istwa',
      computerScience: 'Enfòmatik',
      artsMusic: 'Art ak Mizik',
      
      // Stats
      studentsHelped: 'Elèv ki Jwenn Èd',
      successfulLearners: 'Apranti ki reyisi objektif yo',
      expertTutors: 'Pwofesè Ekspè',
      qualifiedEducators: 'Edikatè kalifye ki pare pou ede',
      subjectsCovered: 'Matyè ki Kouvri',
      diverseTopics: 'Divès sijè akademik',
      successRate: 'To Siksè',
      satisfactionRate: 'To satisfaksyon elèv yo',
      
      // Values
      ourValues: 'Valè Fondamantal Nou yo',
      principlesGuide: 'Prensip ki gide misyon nou pou transfòme edikasyon',
      integrity: 'Entegrite',
      integrityDesc: 'Nou kenbe pi wo nivo konduit pwofesyonèl',
      innovation: 'Aprantisaj Inovatif',
      innovationDesc: 'Itilize teknoloji pou rann edikasyon pi aksesib ak pi angajan pou tout moun.',
      growth: 'Kwasans',
      growthDesc: 'Ankouraje aprantisaj ak devlopman kontinyèl',
      excellence: 'Ekselans',
      excellenceDesc: 'Vize pi bon nan tout sa nou fè',
      
      // Call to Action
      readyToTransform: 'Ou Pare pou Transfòme Pakou Aprantisaj Ou?',
      joinThousands: 'Jwenn ak milye elèv ak pwofesè ki deja fè pati kominote nou an k ap grandi',

      // How It Works Section
      howItWorks: 'Kijan Li Mache',
      searchTeacher: 'Chèche',
      searchTeacherDesc: 'Jwenn pwofesè ki pi bon pou ou selon bezwen w ak kote w ye nan Ayiti.',
      connect: 'Konekte',
      connectDesc: 'Planifye leson yo selon orè ki bon pou ou.',
      learn: 'Aprann',
      learnDesc: 'Resevwa ansèyman pèsonalize epi reyalize objektif ou yo.',
      platformDesc: 'Platfòm nou an fasilite koneksyon ant elèv yo ak pwofesè kalifye nan Ayiti',
      readyToStart: 'Ou pare pou kòmanse pakou aprantisaj ou oswa ofri sèvis ansèyman w ?',
      
      // Why Choose Us Section
      whyChooseUs: 'Poukisa Chwazi LessonPaw',
      committedToEducation: 'Nou angaje nou pou rann edikasyon kalite aksesib atravè Ayiti',
      verifiedTeachers: 'Pwofesè Verifye',
      verifiedTeachersDesc: 'Tout pwofesè yo verifye pou kalifikasyon ak ekspètiz yo nan matyè yo.',
      studentCount: '5,000+ Elèv',
      studentCountDesc: 'Antre nan milye elèv ki deja jwenn pwofesè pafè yo.',
      qualityGuarantee: 'Garanti Kalite',
      qualityGuaranteeDesc: 'Nou asire ansèyman wo kalite oswa nou ofri yon ranplasman san frè adisyonèl.',
      safePayments: 'Pèman Sekirize',
      safePaymentsDesc: 'Tranzaksyon sekirize ak pwoteksyon pèman pou trankilite lespri ou.',
      
      // Teacher Section
      meetExperts: 'Rankontre Pwofesè Ekspè Nou yo',
      teacherDesc: 'Aprann ak edikatè ki gen eksperyans ki pasyone pou ede elèv yo reyisi',
      
      // Success Stories Section
      successStories: 'Istwa Siksè Nou yo',
      successStoriesDesc: 'Dekouvri kijan platfòm nou an te transfòme eksperyans aprantisaj epi ede elèv yo atenn objektif yo',
      viewAllStories: 'Gade Tout Istwa Yo',
      noStories: 'Pa gen istwa siksè pou montre pou kounye a.',
      showLess: 'Montre Mwens',
      closePreview: 'Fèmen Apèsi a',
      
      // Support Section
      support: 'Sipò',
      supportDesc: 'Bezwen èd? Ekip sipò nou an la pou ou',
      contactSupport: 'Kontakte Sipò',
      supportEmail: 'Sipò pa Imèl',
      supportPhone: 'Sipò pa Telefòn',
      supportChat: 'Chat an Dirèk',
      supportHours: 'Orè Sipò',
      supportAvailability: 'Sipò Disponib 24/7',
      supportResponse: 'Tan repons tipik: 2 èdtan',
      supportTicket: 'Kreye Tikè Sipò',
      supportFAQ: 'FAQ',
      supportHelp: 'Bezwen Èd?',
      supportTeam: 'Nou La Pou Ede W',
      support247: 'Sipò 24/7',
      quickResponse: 'Repons Rapid',
      writeMessage: 'Ekri mesaj ou a isit la...',
      sendMessage: 'Voye Mesaj',
      signInToMessage: 'Konekte pou Voye yon Mesaj',
      pleaseLoginMessage: 'Tanpri konekte nan kont ou pou voye nou yon mesaj.',
      
      // What is LesonPaw Section
      whatIsLesonPaw: 'Kisa',
      connectingStudents: 'Konekte elèv yo ak pwofesè pwofesyonèl atravè Ayiti depi 2024',
      qualityEducation: 'Edikasyon Kalite',
      qualityEducationDesc: 'Nou bay aksè a edikasyon kalite siperyè atravè rezo pwofesè pwofesyonèl verifye nou an.',
      connecting: 'Kreye Koneksyon',
      connectingDesc: 'Kreye koneksyon ki gen sans ant elèv ak pwofesè yo pou ankouraje yon anviwònman aprantisaj kolaboratif.',
      innovation: 'Inovasyon nan Edikasyon',
      innovationDesc: 'Itilize teknoloji modèn pou rann edikasyon pi aksesib ak pi enteresan pou tout moun.',
      lesonPawMission: 'Misyon nou se transfòme edikasyon an Ayiti nan fè aprantisaj kalite aksesib pou tout elèv atravè platfòm inovatif nou an.',

      // Contact Page
      getInTouch: 'Contactez',
      contactSubtitle: 'Nous la pour ede w! Voye nou yon mesaj epi nou ap reponn nan 24 èdtan.',
      fullName: 'Non Konplè',
      nameRequired: 'Non an obligatwa',
      emailRequired: 'Imèl la obligatwa',
      invalidEmail: 'Adrès imèl la pa valid',
      phone: 'Nimewo Telefòn',
      optional: 'Opsyonèl',
      subject: 'Sijè',
      subjectRequired: 'Sijè a obligatwa',
      message: 'Mesaj',
      messageRequired: 'Mesaj la obligatwa',
      messageMinLength: 'Mesaj la dwe gen omwen 20 karaktè',
      attachments: 'Dokiman',
      fileUploadInfo: 'Gwosè maksimòm: 5MB. Fòma ki aksepte: PDF, DOC, DOCX, JPG, PNG',
      verifyCaptcha: 'Verifye Captcha',
      enterCaptcha: 'Antre tèks captcha a',
      captchaValidated: 'Captcha Verifye!',
      captchaRequired: 'Captcha Obligatwa',
      pleaseVerifyCaptcha: 'Tanpri verifye captcha a anvan ou soumèt',
      sending: 'Ap voye...',
      responseTime: 'Nou ap reponn ou nan 24 èdtan.',
      submissionFailed: 'Echèk nan Voye',
      tryAlternativeContact: 'Tanpri eseye ankò pita',
      businessHours: 'Orè Biznis',
      mondayFriday: 'Lendi - Vandredi',
      saturday: 'Samdi',
      sunday: 'Dimanch',
      closed: 'Fèmen',
      timeZone: 'Tout lè yo se nan Lè Lès (ET)',
      contactInfo: 'Enfòmasyon Kontak',
      address: 'Adrès',
      connectWithUs: 'Konekte ak Nou',
      ourLocation: 'Lokalizasyon Nou',
      getDirections: 'Jwenn Direksyon',

      // Dashboard Menu
      manageProfile: 'Jere Pwofil',
      myBookings: 'Rezèvasyon Mwen',
      joinAsTeacher: 'Vin yon Pwofesè',
      postJob: 'Poste Travay',
      myPosts: 'Piblikasyon Mwen',
      availableJobs: 'Travay Disponib',
      manageServices: 'Jere Sèvis',
      manageUsers: 'Jere Itilizatè',
      allTutors: 'Tout Pwofesè',
      showMessages: 'Montre Mesaj',
      addTutor: 'Ajoute Pwofesè',
      applications: 'Aplikasyon',
      payments: 'Peman',
      analytics: 'Analiz',
      students: 'Elèv',
      allJobs: 'Tout Travay',
      allServices: 'Tout Sèvis',
      story: 'Istwa',
      manageStory: 'Jere Istwa',
      addBlog: 'Ajoute Blog',
      editBlog: 'Modifye Blog',
      confirmation: 'Konfimasyon yo',
      menu: 'Meni',

      // Find Teacher Guide
      findPerfectTeacher: 'Jwenn Pwofesè Pafè Ou',
      findTeacherDesc: 'Dekouvri edikatè ekspè ki pral gide ou nan ekselans akademik ak kwasans pèsonèl',
      smartSearch: 'Rechèch Entèlijan',
      smartSearchDesc: 'Sistèm match entèlijan nou an ede ou jwenn pwofesè pafè a selon objektif aprantisaj ou, matyè ou prefere, ak orè ou.',
      expertVerification: 'Verifikasyon Ekspè',
      expertVerificationDesc: 'Chak pwofesè pase nan yon pwosesis verifikasyon rigoureux. Gade pwofil detaye ak referans verifye, eksperyans, ak opinyon elèv yo.',
      flexibleLearning: 'Aprantisaj Fleksib',
      flexibleLearningDesc: 'Chwazi ant sesyon sou entènèt oswa an pèsòn. Planifye leson ki adapte ak style lavi ou ak sistèm rezèvasyon fasil nou an.',
      personalizedExperience: 'Eksperyans Pèsonalize',
      personalizedExperienceDesc: 'Jwi plan aprantisaj pèsonalize, swivi pwogrè, ak sipò kontinyèl pandan tout pakou edikasyonèl ou.',
      verifiedTeachers: 'Pwofesè Verifye',
      verifiedTeachersCount: 'Pwofesè Verifye',
      subjectsOffered: 'Matyè Disponib',
      studentSatisfaction: 'Satisfaksyon Elèv',
      learningJourneyStart: 'Pakou Aprantisaj Ou Kòmanse Isit',
      whyStudentsChooseUs: 'Poukisa Elèv Yo Chwazi Nou',
      expertTeachers: 'Pwofesè Ekspè',
      expertTeachersDesc: 'Aprann ak pwofesyonèl sètifye ki gen eksperyans pwouve',
      modernLearningTools: 'Zouti Aprantisaj Modèn',
      modernLearningToolsDesc: 'Aksè a resous edikasyonèl ak teknoloji dènye kri',
      communitySupport: 'Sipò Kominote',
      communitySupportDesc: 'Antre nan yon kominote aprantisaj dinamik elèv ak edikatè',
      startLearningToday: 'Kòmanse Aprann Jodi a',
      learnMoreAboutUs: 'Aprann Plis Sou Nou',

      // Become Teacher Guide
      becomeExpertTeacher: 'Devenez un Professeur Expert',
      becomeTeacherDesc: 'Partagez vos connaissances, inspirez les étudiants et construisez une carrière enrichissante dans l\'enseignement sur notre plateforme',
      teacherProfile: 'Construisez Votre Profil',
      buildProfileDesc: 'Créez un profil d\'enseignement convaincant qui montre votre expertise, votre méthodologie d\'enseignement et vos réalisations professionnelles.',
      qualityVerification: 'Vérification de Qualité',
      qualityVerificationDesc: 'Notre processus de vérification rigoureux assure des standards d\'enseignement élevés. Soumettez vos références et certifications.',
      customizeTeaching: 'Personnalisez Votre Enseignement',
      customizeTeachingDesc: 'Définissez vos préférences d\'enseignement, vos tarifs et votre disponibilité. Choisissez entre l\'enseignement en ligne et en personne.',
      startJourney: 'Commencez Votre Parcours',
      startJourneyDesc: 'Connectez-vous avec des étudiants, donnez des cours intéressants et développez votre activité d\'enseignement sur notre plateforme.',
      professionalGrowth: 'Croissance Professionnelle',
      professionalGrowthDesc: 'Accédez à des ressources de développement professionnel et construisez votre portfolio d\'enseignement',
      teachingTools: 'Outils d\'Enseignement',
      teachingToolsDesc: 'Utilisez notre plateforme et nos ressources d\'enseignement avancées',
      careerDevelopment: 'Développement de Carrière',
      careerDevelopmentDesc: 'Élargissez votre portée et développez votre carrière d\'enseignant',
      flexibleSchedule: 'Horaires Flexibles',
      flexibleScheduleDesc: 'Travaillez selon vos conditions',
      platformSupport: 'Support de la Plateforme',
      platformSupportDesc: 'Toujours là pour vous aider',
      earningPotential: 'Potentiel de Revenus',
      earningPotentialDesc: 'Fixez vos propres tarifs',
      teachingJourneyBegins: 'Votre Parcours d\'Enseignement Commence Ici',
      teachingBenefits: 'Avantages de l\'Enseignement Avec Nous',
      readyToTeach: 'Prêt à Commencer Votre Parcours d\'Enseignement ?',
      joinTeacherCommunity: 'Rejoignez notre communauté d\'éducateurs passionnés et faites une différence dans la vie des étudiants',
      applyAsTeacher: 'Postuler Comme Professeur',
      learnMoreTeaching: 'En Savoir Plus sur l\'Enseignement',

      // Blog Page
      discoverKnowledge: 'Découvrez',
      insights: 'Perspectives',
      blogDescription: 'Explorez des articles intéressants, des conseils d\'experts et des histoires inspirantes provenant de notre communauté d\'éducateurs et d\'apprenants.',
      searchBlogsPlaceholder: 'Rechercher des articles par titre, catégorie ou contenu...',
      popular: 'Populaire',
      teachingTips: 'Conseils d\'Enseignement',
      studyGuides: 'Guides d\'Étude',
      learningResources: 'Ressources d\'Apprentissage',
      studentSuccess: 'Réussites des Étudiants',
      allCategories: 'Toutes les Catégories',
      noPostsFound: 'Aucun article trouvé',
      adjustSearchOrCategory: 'Essayez d\'ajuster votre recherche ou votre filtre de catégorie',
      readMore: 'Lire la suite',
      tags: 'Étiquettes',
      education: 'Éducation',
      technology: 'Technologie',
      learning: 'Apprentissage',
      teaching: 'Enseignement',
      students: 'Étudiants',
      tips: 'Conseils',
      recentPosts: 'Articles récents',
      failedToLoadBlogs: 'Échec du chargement des articles',
      errorLoadingBlogs: 'Erreur de chargement des articles',
      tryAgainLater: 'Veuillez réessayer plus tard',
      readTime: 'Temps de lecture',
      author: 'Auteur',
      relatedTopics: 'Sujets Connexes',

      // Our Journey Section
      ourJourney: 'Pakou Nou',
      journeySubtitle: 'Dekouvri kijan nou evolye pou nou vin platfòm edikasyon prensipal an Ayiti',
      ideaLaunch: 'Lansman Lide a',
      ideaLaunchDesc: 'LesonPaw te fonde ak vizyon pou transfòme edikasyon an Ayiti',
      prototypeTitle: 'Lansman Premye Pwototip',
      prototypeDesc: 'Nou te rive nan premye etap nou pou ede elèv yo',
      webLaunchTitle: 'Lansman Aplikasyon Web',
      webLaunchDesc: 'Nou te elaji pòte nou ak yon aplikasyon Web dedye',
      recognitionTitle: 'Rekonesans Nasyonal',
      recognitionDesc: 'Rekonèt kòm platfòm edikasyon lidè an Ayiti',

      // Meet Team Section
      meetTeam: 'Rankontre Ekip Nou',
      teamSubtitle: 'Pwofesyonèl pasyone kap travay pou transfòme edikasyon an Ayiti',
      founderRole: 'Fondatè & PDG',
      founderBio: 'Pasyone pou rann edikasyon aksesib pou tout elèv ayisyen',
      educationRole: 'Direktris Edikasyon',
      educationBio: 'Ekspè nan devlopman kourikoulòm ak plis pase 10 ane eksperyans nan ansèyman',
      techRole: 'Direktè Teknik',
      techBio: 'Asire eksperyans aprantisaj san pwoblèm atravè teknoloji',
      achievements: 'Reyalizasyon',
      yearsInEdTech: '10+ ane nan EdTech',
      harvardGrad: 'Diplome Harvard Business School',
      educationAward: 'Pri Inovasyon Edikasyon 2023',
      formerProf: 'Ansyen Pwofesè Inivèsite',
      publishedAuthor: 'Otè Pibliye nan Edikasyon',
      teachingAward: 'Pri Nasyonal Ekselans nan Ansèyman',
      yearsInTech: '15+ ane nan Teknoloji',
      mitGrad: 'MIT nan Enfòmatik',
      techPatents: 'Plizyè Brevet Teknolojik',

      // Become Teacher Guide Page
      becomeExpertTeacher: 'Vin yon Pwofesè Ekspè',
      becomeTeacherDesc: 'Pataje konesans ou, enspire elèv yo epi bati yon karyè anrichisman nan ansèyman sou platfòm nou an',
      
      // Features
      flexibleSchedule: 'Orè Fleksib',
      flexibleScheduleDesc: 'Travay selon kondisyon pa w',
      platformSupport: 'Sipò Platfòm',
      platformSupportDesc: 'Toujou la pou ede w',
      earningPotential: 'Potansyèl Revni',
      earningPotentialDesc: 'Fikse pwòp tarif ou',

      // Steps
      teachingJourneyBegins: 'Pakou Ansèyman w Kòmanse La',
      buildProfile: 'Kreye Pwofil ou',
      buildProfileDesc: 'Kreye yon pwofil pwofesyonèl ki montre eksperyans ou ak domèn ekspètiz ou',
      qualityVerification: 'Verifikasyon Kalite',
      qualityVerificationDesc: 'Nou verifye kalifikasyon w pou asire pi bon kalite ansèyman',
      customizeTeaching: 'Pèsonalize Ansèyman w',
      customizeTeachingDesc: 'Chwazi matyè w, orè w, ak metòd ansèyman w',
      startJourney: 'Kòmanse Pakou w',
      startJourneyDesc: 'Kòmanse konekte ak elèv epi bati repitasyon w',

      // Benefits
      teachingBenefits: 'Avantaj Ansèyman',
      professionalGrowth: 'Kwasans Pwofesyonèl',
      professionalGrowthDesc: 'Devlope konpetans ou ak eksperyans ou nan ansèyman',
      teachingTools: 'Zouti Ansèyman',
      teachingToolsDesc: 'Aksè a zouti modèn pou fasilite ansèyman',
      careerDevelopment: 'Devlopman Karyè',
      careerDevelopmentDesc: 'Opòtinite pou w grandi kòm edikatè',

      // CTA
      readyToTeach: 'Pare pou Anseye?',
      joinTeacherCommunity: 'Antre nan kominote pwofesè nou an epi kòmanse pakou ansèyman w jodi a',
      applyAsTeacher: 'Aplike kòm Pwofesè',
      learnMoreTeaching: 'Aprann Plis',

      // Why Choose LessonPaw Section
      whyChoose: 'Poukisa Chwazi',
      ourCommitment: 'Nou angaje nou pou rann edikasyon kalite aksesib atravè Ayiti',
      verifiedProfessors: 'Pwofesè Verifye',
      allProfessorsVerified: 'Tout pwofesè yo verifye pou kalifikasyon ak ekspètiz yo',
      studentCount: '5,000+ Elèv',
      studentCountDesc: 'Jwenn ak milye elèv ki deja jwenn pwofesè pafè yo',
      qualityGuarantee: 'Garanti Kalite',
      qualityGuaranteeDesc: 'Nou garanti ansèyman kalite oswa nou ofri yon ranplasman san frè',
      securePayment: 'Peman Sekirize',
      securePaymentDesc: 'Opsyon peman sekirize ki gen ladan mobile money popilè an Ayiti',
      
      // Stats
      professorsVerified: '1,200+ Pwofesè Verifye',
      lessonsCompleted: '25,000+ Leson Konplete',
      satisfactionRate: '95% To satisfaksyon elèv yo',
      citiesInHaiti: '32 Vil nan Ayiti',
      
      // CTA Button
      joinCommunity: 'Antre nan Kominote Nou'
    }
  }
};

// Language Provider Component
const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('fr');

  const translate = (key) => {
    return languages[currentLanguage]?.translations[key] || languages.en.translations[key] || key;
  };

  const value = {
    currentLanguage,
    setCurrentLanguage,
    translate,
    languages
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook for using language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageProvider; 